import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  indexSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ]
  // By default, Docusaurus generates a sidebar from the docs folder structure
};

export default sidebars;
