import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  indexSidebar: [
    'changelog',
    {
      // ref https://docusaurus.io/docs/sidebar/items#sidebar-item-category
      type: 'category',
      label: 'Resource',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'resource'
        }
      ]
    },
    {
      type: 'category',
      label: 'Personal Project',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'personalProject'
        }
      ]
    }
  ]
  // By default, Docusaurus generates a sidebar from the docs folder structure
}

export default sidebars
